#!/usr/bin/env bash
# This script is to displays the content of the file /etc/passwd

while IFS=: read -r username password uid gid info home shell; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd