#!/usr/bin/env bash
# This script is to displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username password uid gid info home shell; do
    echo "The user $username is part of the $gid gang,"
    echo "lives in $home and rides $shell."
    echo "USER ID's place is protected by the passcode $password,"
    echo "more info about the user here: $uid $info"
    echo
done < /etc/passwd