#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

text="Best School"
badluck="bad luck"
goodluck="good luck"
count=1

while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "$badluck"
    elif [ $count -eq 8 ]; then
        echo "$goodluck"
    else
        echo "$text"
    fi
    ((count++))
done