#!/usr/bin/env bash
# This script displays "Best School" 10 times

china="bad luck from China"
japan="bad luck from Japan"
italy="bad luck from Italy"
count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo "$china"
            ;;
        9)
            echo "$japan"
            ;;
        17)
            echo "$italy"
            ;;
        *)
            echo "$count"
            ;;
    esac
    ((count++))
done